### ISSUE TITLE
404 When tab includes diacritics?

### ISSUE THREAD

**Issue by TobTobXX** [pavo-etc/penultimate-guitar#37]
Hi! I've been enjoying Penultimate Guitar immensly. Thank you so much for making this project!!

I'm German (well, Swiss actually) and I like to play German (well, Swiss German) songs from time to time. These often include Umlate (ä, ü, ö) in their title or in the singer name. Whenever I try to open one of these songs (they appear in the search results just fine), the site shows a 404 error.

I did some further testing and it appears to happen with french diacritics too. Maybe an URL en-/decoding issue?

Example links:
- https://pg.zachmanson.com/tab/1152193 (Schwan - Gölä)
- https://pg.zachmanson.com/tab/3264326 (Keini Träne Meh - Gölä)
- https://pg.zachmanson.com/tab/3962218 (Libéré - Stress)

**Comment by pavo-etc** [comment]
Oh wow I didn't know ultimate guitar had URLs like this.  Good catch

**Comment by pavo-etc** [comment]
Seems like its not just diacritics but any Unicode values outside of UTF.  This is because those characters aren't allowed in URLs and need to be percent encoded, which I guess the devs at UG just sidestepped entirely by using the song id.

**Comment by pavo-etc** [comment]
Resolved, now works
<img width="1552" alt="Screen Shot 2023-05-02 at 6 18 21 pm" src="https://user-images.githubusercontent.com/24368336/235641110-41e3fab0-2039-42a1-a5c9-271a9c113c59.png">

**Comment by TobTobXX** [comment]
Can confirm, thank yoouuuuuu! :smile:
